export const siteConfig = {
  name: "Máster Fintech, Blockchain y Mercados Financieros",
  shortName: "Máster Fintech UB",
  university: "Universitat de Barcelona",
  faculty: "Facultat d'Economia i Empresa",
  description:
    "El Máster de Fintech, Blockchain y Mercados Financieros te convertirá en experto en la industria financiera que aplica nuevas tecnologías a actividades financieras y de inversión. Edición 2026-27 · 60 ECTS · Universitat de Barcelona.",
  url: "https://www.ub.edu/fintech",
  locale: "es_ES",
  phone: "+34 677 40 40 98",
  email: "drey@ub.edu",
  whatsapp: "34677404098",
  edition: "2026-27",
  seatsLeft: 9,
  seats: 40,
  price: "5.480 €",
  priceValue: "5480",
  ects: 60,
  deposit: "900 €",
  schedule: "Martes, miércoles y jueves, 18:00–21:00",
  modality: "Presencial, semipresencial u online",
  language: "Español",
  preinscription: "Del 1 de marzo al 13 de octubre de 2026",
  academicPeriod: "Del 13 de octubre de 2026 al 10 de septiembre de 2027",
  academicPeriodShort: "Oct 2026 – Sep 2027",
  campusVirtual: "https://campusvirtual.ub.edu/",
  planDocente: "/uploads/2026/06/Plan-Docente-Master-Fintech-2026-27.pdf",
  alumniUrl: "https://app-master-ia-fintech.ub.edu/",
  masterIaUrl: "https://ub.edu/ai/",
  address: "Facultat d'Economia i Empresa · Universitat de Barcelona",
} as const;

export const navItems = [
  { href: "/", label: "Inicio" },
  { href: "/plan-de-estudio", label: "Plan de estudio" },
  { href: "/profesores", label: "Profesores" },
  { href: "/practicas-y-empresas", label: "Empresas" },
  { href: "/noticias-master", label: "Noticias" },
  { href: "/inscripciones-y-becas", label: "Inscripciones" },
  {
    href: "https://app-master-ia-fintech.ub.edu/",
    label: "Alumni",
    external: true,
  },
  { href: "/investigacion-y-emprendimiento", label: "Investigación" },
  { href: "/contacto", label: "Contacto" },
] as const;
